name: 'Compile NAV/Business Central App'
description: 'Compiles an NAV/Business Central App in an container.'
branding:
  icon: 'box'
  color: green

inputs:
  username:
    description: "The username for the NAV user."
    required: false
    default: "admin"
  password:
    description: "The password for the NAV user."
    required: false
    default: "P@ssword1"
  name:
    description: "The name of the container."
    required: false
    default: "BC"
  current_version:
    description: "The current version of the app to use for validation."
    required: false
    default: ""

outputs:
  app:
    description: "Compiled App"
    value: ${{ steps.compile-app.outputs.app }}

runs:
  using: composite

  steps:
    - id: compile-app
      shell: powershell
      run: ${{ github.action_path }}/compile.ps1
      env:
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_CURRENT: ${{ inputs.current }}
