name: 'Download Artifact'
description: 'Downloads the chosen NAV/BC artifact.'
branding:
  icon: 'download'
  color: green

inputs:
  country:
    description: "Set to download a country specific artifact."
    required: false
    default: "w1"
  version:
    description: "The NAV/BC version an artifact should be downloaded for."
    required: true
  type:
    description: "Controls of the selected artifact should be sandbox or on-prem."
    required: false
    default: "OnPrem"
  select:
    description: "The strategy to use when selecting versions"
    required: false
  sasKey:
    description: "Authentication token for downloading master releases"
    required: false
    default: ""

outputs:
  artifact:
    description: "Artifact"
    value: ${{ steps.download-artifact.outputs.artifact }}

runs:
  using: composite

  steps:
    - id: download-artifact
      shell: powershell
      run: ${{ github.action_path }}/download.ps1
      env:
        INPUT_COUNTRY: ${{ inputs.country }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_TYPE: ${{ inputs.type }}
        INPUT_SELECT: ${{ inputs.select }}
        INPUT_TOKEN: ${{ inputs.sasKey }}
