name: 'Create Container'
description: 'Start a NAV/BC container using the given artifact.'
branding:
  icon: 'battery-charging'
  color: green

inputs:
  artifact:
    description: "The URL to the artifact to use."
    required: true
  username:
    description: "The username for the NAV user."
    required: false
    default: "admin"
  password:
    description: "The password for the NAV user."
    required: false
    default: "P@ssword1"
  name:
    description: "The name of the container."
    required: false
    default: "BC"
  license:
    description: "The license file content, base64 encoded."
    required: false
  license_is_flf:
    description: "Set to true if the license is FLF otherwise bclicense is expected."
    required: false

outputs:
  name:
    description: "Container Name"
    value: ${{ steps.create-container.outputs.name }}

runs:
  using: composite

  steps:
    - id: create-container
      shell: powershell
      run: ${{ github.action_path }}/create.ps1
      env:
        INPUT_ARTIFACT: ${{ inputs.artifact }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_LICENSE: ${{ inputs.license }}
        INPUT_LICENSE_IS_FLF: ${{ inputs.license_if_flf }}
